# Generated by Django 4.1.4 on 2022-12-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glider_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.IntegerField(verbose_name='Mission #')),
            ],
        ),
        migrations.AddField(
            model_name='glider',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gliders', to='glider_reader.mission', verbose_name='Mission #'),
        ),
    ]
